-- Maj_Consultation_De_Donnees_BoatBooking_Hoareau_Diallo_Aittahar.sql

----------------CONSULTATION - 5 requêtes impliquant 1 table dont 1 avec un group By----------------

-- [Description de la requete...]
SELECT ... 
FROM ...
WHERE ...

-- [Description de la requete...]
SELECT ... 
FROM ...
WHERE ...

...

----------------CONSULTATION - Une req avec un Order By----------------

-- [Description de la requete...]
SELECT ... 
FROM ...
WHERE ...


----------------UPDATE -  2 requêtes impliquant 1 table----------------

-- Jean veut corriger son prénom, il s'est trompé, il a enregistré Aimee à la place de son prénom
UPDATE CLIENT
SET CL_PRENOM = 'Jean'
WHERE CL_PRENOM = 'Aimee' and CL_NOM = 'Johnson';

-- [Description de la requete...]
UPDATE ...
SET ...
WHERE ...

